In [127]:
import numpy as np
import pandas as pd

In [128]:
df = pd.read_csv("dataset/Housing.csv")
df

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [129]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [130]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


In [131]:
df.shape

(545, 13)

In [132]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

In [133]:
x = pd.DataFrame(df)

In [134]:
x.drop(columns=['price'],inplace=True)

In [135]:
x

area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    7420         4          2        3      yes        no       no   
1    8960         4          4        4      yes        no       no   
2    9960         3          2        2      yes        no      yes   
3    7500         4          2        2      yes        no      yes   
4    7420         4          1        2      yes       yes      yes   
..    ...       ...        ...      ...      ...       ...      ...   
540  3000         2          1        1      yes        no      yes   
541  2400         3          1        1       no        no       no   
542  3620         2          1        1      yes        no       no   
543  2910         3          1        1       no        no       no   
544  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 12 columns]

In [136]:
y = pd.DataFrame(df['price'])

In [137]:
y

price
0    13300000
1    12250000
2    12250000
3    12215000
4    11410000
..        ...
540   1820000
541   1767150
542   1750000
543   1750000
544   1750000

[545 rows x 1 columns]

In [138]:
x_train,x_test,y_train,y_test = train_test_split(x , y , test_size=0.2)

In [139]:
x_train.shape

(436, 12)

In [140]:
x_test.shape

(109, 12)

In [141]:
y_train.shape

(436, 1)

In [142]:
y_test.shape

(109, 1)

In [143]:
tr = ColumnTransformer(transformers=[
    ('t1',OrdinalEncoder(categories=[['furnished','semi-furnished','unfurnished']]),['furnishingstatus']),
    ('t2',OneHotEncoder(drop='first',sparse=False),['mainroad','guestroom','basement','hotwaterheating','airconditioning','prefarea'])
] , remainder='passthrough')

In [144]:
tr

ColumnTransformer(remainder='passthrough',
                  transformers=[('t1',
                                 OrdinalEncoder(categories=[['furnished',
                                                             'semi-furnished',
                                                             'unfurnished']]),
                                 ['furnishingstatus']),
                                ('t2',
                                 OneHotEncoder(drop='first', sparse=False),
                                 ['mainroad', 'guestroom', 'basement',
                                  'hotwaterheating', 'airconditioning',
                                  'prefarea'])])

In [145]:
a = tr.fit_transform(x_train)

In [146]:
a

array([[2., 0., 0., ..., 1., 1., 0.],
       [2., 1., 0., ..., 1., 1., 2.],
       [1., 1., 0., ..., 2., 2., 0.],
       ...,
       [0., 1., 0., ..., 2., 2., 1.],
       [2., 1., 0., ..., 1., 1., 2.],
       [1., 1., 0., ..., 1., 2., 3.]])

In [147]:
b = tr.fit_transform(x_test)

In [148]:
b

array([[0., 1., 1., ..., 2., 1., 0.],
       [1., 1., 0., ..., 1., 2., 0.],
       [0., 1., 1., ..., 1., 1., 2.],
       ...,
       [2., 1., 0., ..., 1., 1., 2.],
       [0., 1., 0., ..., 1., 1., 1.],
       [0., 1., 0., ..., 1., 3., 0.]])

In [149]:
from sklearn.linear_model import LinearRegression

In [150]:
lr = LinearRegression()

In [151]:
lr.fit(a,y_train)

LinearRegression()

In [152]:
lr.predict(b)

array([[5528815.75806957],
       [4135474.71297967],
       [5124042.77377987],
       [3611621.35943374],
       [3380096.84948811],
       [4076868.76161721],
       [4122164.56568621],
       [6885413.06888886],
       [5606883.57522535],
       [3995385.84294124],
       [6471044.22548772],
       [5986368.82253724],
       [6763237.95519411],
       [3795003.6466306 ],
       [5413112.57394376],
       [7232491.20610542],
       [7284061.5015553 ],
       [6558166.57992907],
       [2124642.32590377],
       [2822283.58522024],
       [3505175.12006949],
       [5757628.11411701],
       [2270621.18485116],
       [3014464.71730391],
       [4270248.48066387],
       [3931589.53734231],
       [5172258.24168463],
       [4341019.56142556],
       [2044291.60164921],
       [5368488.77367276],
       [3187483.88469107],
       [7370535.24430231],
       [4139815.79777325],
       [3316378.96568698],
       [4724117.6316311 ],
       [5050555.30392117],
       [3799296.82104172],
 

In [153]:
lr.score(a,Y_train)

-0.6824596194467523

In [154]:
lr.score(b,Y_test)

-1.2172437694003246