In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("dataset/tips.csv")
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [3]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [4]:
df.shape

(244, 7)

(244, 7)

In [5]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

In [6]:
X = df.drop(columns=['tip'])
X

total_bill     sex smoker   day    time  size
0         16.99  Female     No   Sun  Dinner     2
1         10.34    Male     No   Sun  Dinner     3
2         21.01    Male     No   Sun  Dinner     3
3         23.68    Male     No   Sun  Dinner     2
4         24.59  Female     No   Sun  Dinner     4
..          ...     ...    ...   ...     ...   ...
239       29.03    Male     No   Sat  Dinner     3
240       27.18  Female    Yes   Sat  Dinner     2
241       22.67    Male    Yes   Sat  Dinner     2
242       17.82    Male     No   Sat  Dinner     2
243       18.78  Female     No  Thur  Dinner     2

[244 rows x 6 columns]

total_bill     sex smoker   day    time  size
0         16.99  Female     No   Sun  Dinner     2
1         10.34    Male     No   Sun  Dinner     3
2         21.01    Male     No   Sun  Dinner     3
3         23.68    Male     No   Sun  Dinner     2
4         24.59  Female     No   Sun  Dinner     4
..          ...     ...    ...   ...     ...   ...
239       29.03    Male     No   Sat  Dinner     3
240       27.18  Female    Yes   Sat  Dinner     2
241       22.67    Male    Yes   Sat  Dinner     2
242       17.82    Male     No   Sat  Dinner     2
243       18.78  Female     No  Thur  Dinner     2

[244 rows x 6 columns]

In [7]:
df['day'].unique()

array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object)

array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object)

In [8]:
Y = df[['tip']]
Y

tip
0    1.01
1    1.66
2    3.50
3    3.31
4    3.61
..    ...
239  5.92
240  2.00
241  2.00
242  1.75
243  3.00

[244 rows x 1 columns]

tip
0    1.01
1    1.66
2    3.50
3    3.31
4    3.61
..    ...
239  5.92
240  2.00
241  2.00
242  1.75
243  3.00

[244 rows x 1 columns]

In [9]:
X_train,X_test,Y_train,Y_test = train_test_split(X , Y , test_size=0.2 , train_size=0.8)

In [10]:
X_train

total_bill     sex smoker   day    time  size
154       19.77    Male     No   Sun  Dinner     4
110       14.00    Male     No   Sat  Dinner     2
104       20.92  Female     No   Sat  Dinner     2
78        22.76    Male     No  Thur   Lunch     2
177       14.48    Male    Yes   Sun  Dinner     2
..          ...     ...    ...   ...     ...   ...
103       22.42  Female    Yes   Sat  Dinner     2
242       17.82    Male     No   Sat  Dinner     2
214       28.17  Female    Yes   Sat  Dinner     3
233       10.77    Male     No   Sat  Dinner     2
102       44.30  Female    Yes   Sat  Dinner     3

[195 rows x 6 columns]

total_bill     sex smoker   day    time  size
154       19.77    Male     No   Sun  Dinner     4
110       14.00    Male     No   Sat  Dinner     2
104       20.92  Female     No   Sat  Dinner     2
78        22.76    Male     No  Thur   Lunch     2
177       14.48    Male    Yes   Sun  Dinner     2
..          ...     ...    ...   ...     ...   ...
103       22.42  Female    Yes   Sat  Dinner     2
242       17.82    Male     No   Sat  Dinner     2
214       28.17  Female    Yes   Sat  Dinner     3
233       10.77    Male     No   Sat  Dinner     2
102       44.30  Female    Yes   Sat  Dinner     3

[195 rows x 6 columns]

In [11]:
X_test.shape

(49, 6)

(49, 6)

In [12]:
Y_train.shape

(195, 1)

(195, 1)

In [13]:
Y_test.shape

(49, 1)

(49, 1)

In [14]:
tr = ColumnTransformer(transformers=[
    ('trn1',OrdinalEncoder(categories=[['Thur', 'Fri', 'Sat', 'Sun']]),['day']),
    ('trn2',OneHotEncoder(drop='first',sparse=False),['sex','smoker','time']),
#     ('trn3',OneHotEncoder(drop='first',sparse=False),['smoker']),
#     ('trn4',OneHotEncoder(drop='first',sparse=False),['time'])
],remainder='passthrough')

In [15]:
tr

ColumnTransformer(remainder='passthrough',
                  transformers=[('trn1',
                                 OrdinalEncoder(categories=[['Thur', 'Fri',
                                                             'Sat', 'Sun']]),
                                 ['day']),
                                ('trn2',
                                 OneHotEncoder(drop='first', sparse=False),
                                 ['sex', 'smoker', 'time'])])

ColumnTransformer(remainder='passthrough',
                  transformers=[('trn1',
                                 OrdinalEncoder(categories=[['Thur', 'Fri',
                                                             'Sat', 'Sun']]),
                                 ['day']),
                                ('trn2',
                                 OneHotEncoder(drop='first', sparse=False),
                                 ['sex', 'smoker', 'time'])])

In [16]:
tr.fit_transform(X_train)

array([[ 3.  ,  1.  ,  0.  ,  0.  , 19.77,  4.  ],
       [ 2.  ,  1.  ,  0.  ,  0.  , 14.  ,  2.  ],
       [ 2.  ,  0.  ,  0.  ,  0.  , 20.92,  2.  ],
       ...,
       [ 2.  ,  0.  ,  1.  ,  0.  , 28.17,  3.  ],
       [ 2.  ,  1.  ,  0.  ,  0.  , 10.77,  2.  ],
       [ 2.  ,  0.  ,  1.  ,  0.  , 44.3 ,  3.  ]])

array([[ 3.  ,  1.  ,  0.  ,  0.  , 19.77,  4.  ],
       [ 2.  ,  1.  ,  0.  ,  0.  , 14.  ,  2.  ],
       [ 2.  ,  0.  ,  0.  ,  0.  , 20.92,  2.  ],
       ...,
       [ 2.  ,  0.  ,  1.  ,  0.  , 28.17,  3.  ],
       [ 2.  ,  1.  ,  0.  ,  0.  , 10.77,  2.  ],
       [ 2.  ,  0.  ,  1.  ,  0.  , 44.3 ,  3.  ]])

In [17]:
tr.fit_transform(X_train).shape

(195, 6)

(195, 6)

In [18]:
tr.fit_transform(X_test)

array([[ 0.  ,  0.  ,  0.  ,  1.  ,  8.35,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  1.  ,  7.56,  2.  ],
       [ 3.  ,  1.  ,  0.  ,  0.  , 48.17,  6.  ],
       [ 2.  ,  1.  ,  1.  ,  0.  , 15.69,  3.  ],
       [ 3.  ,  0.  ,  0.  ,  0.  , 16.97,  3.  ],
       [ 0.  ,  0.  ,  1.  ,  1.  , 12.74,  2.  ],
       [ 3.  ,  0.  ,  1.  ,  0.  ,  9.6 ,  2.  ],
       [ 0.  ,  1.  ,  1.  ,  1.  , 15.48,  2.  ],
       [ 3.  ,  1.  ,  0.  ,  0.  , 28.55,  3.  ],
       [ 2.  ,  0.  ,  1.  ,  0.  , 30.14,  4.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  , 13.16,  2.  ],
       [ 2.  ,  1.  ,  0.  ,  0.  , 10.51,  2.  ],
       [ 2.  ,  1.  ,  1.  ,  0.  , 11.59,  2.  ],
       [ 2.  ,  1.  ,  0.  ,  0.  , 17.59,  3.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 18.78,  2.  ],
       [ 3.  ,  0.  ,  1.  ,  0.  , 17.51,  2.  ],
       [ 2.  ,  1.  ,  1.  ,  0.  , 13.81,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  8.51,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  , 24.08,  4.  ],
       [ 1.  ,  0.  ,  1.  ,  0

array([[ 0.  ,  0.  ,  0.  ,  1.  ,  8.35,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  1.  ,  7.56,  2.  ],
       [ 3.  ,  1.  ,  0.  ,  0.  , 48.17,  6.  ],
       [ 2.  ,  1.  ,  1.  ,  0.  , 15.69,  3.  ],
       [ 3.  ,  0.  ,  0.  ,  0.  , 16.97,  3.  ],
       [ 0.  ,  0.  ,  1.  ,  1.  , 12.74,  2.  ],
       [ 3.  ,  0.  ,  1.  ,  0.  ,  9.6 ,  2.  ],
       [ 0.  ,  1.  ,  1.  ,  1.  , 15.48,  2.  ],
       [ 3.  ,  1.  ,  0.  ,  0.  , 28.55,  3.  ],
       [ 2.  ,  0.  ,  1.  ,  0.  , 30.14,  4.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  , 13.16,  2.  ],
       [ 2.  ,  1.  ,  0.  ,  0.  , 10.51,  2.  ],
       [ 2.  ,  1.  ,  1.  ,  0.  , 11.59,  2.  ],
       [ 2.  ,  1.  ,  0.  ,  0.  , 17.59,  3.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 18.78,  2.  ],
       [ 3.  ,  0.  ,  1.  ,  0.  , 17.51,  2.  ],
       [ 2.  ,  1.  ,  1.  ,  0.  , 13.81,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  8.51,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  , 24.08,  4.  ],
       [ 1.  ,  0.  ,  1.  ,  0

In [19]:
tr.fit_transform(X_test).shape

(49, 6)

(49, 6)